version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./project:/var/www/html
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./project:/var/www/html
