version: '3.8'

services:
  nginx:
    image: nginx
    container_name: mynginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    container_name: myphp
    volumes:
      - ./php:/var/www/html
